language: python
python:
    - "3.6"
install:
    - pip install nose
script:
    - nosetests
notifications:
    email:
        recipients:
            - shining_0212@163.com
        on_success: always
        on_failure: always
        
